In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt




from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import ExtraTreesClassifier



In [3]:
df=pd.read_csv('banking.csv')
df.head(5)

age          job  marital          education  default housing loan  \
0   44  blue-collar  married           basic.4y  unknown     yes   no   
1   53   technician  married            unknown       no      no   no   
2   28   management   single  university.degree       no     yes   no   
3   39     services  married        high.school       no      no   no   
4   55      retired  married           basic.4y       no     yes   no   

    contact month day_of_week  ...  campaign  pdays  previous     poutcome  \
0  cellular   aug         thu  ...         1    999         0  nonexistent   
1  cellular   nov         fri  ...         1    999         0  nonexistent   
2  cellular   jun         thu  ...         3      6         2      success   
3  cellular   apr         fri  ...         2    999         0  nonexistent   
4  cellular   aug         fri  ...         1      3         1      success   

  emp_var_rate  cons_price_idx  cons_conf_idx  euribor3m  nr_employed  y  
0          1.4          93.444          -36.1      4.963       5228.1  0  
1         -0.1          93.200          -42.0      4.021       5195.8  0  
2         -1.7          94.055          -39.8      0.729       4991.6  1  
3         -1.8          93.075          -47.1      1.405       5099.1  0  
4         -2.9          92.201          -31.4      0.869       5076.2  1  

[5 rows x 21 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
age               41188 non-null int64
job               41188 non-null object
marital           41188 non-null object
education         41188 non-null object
default           41188 non-null object
housing           41188 non-null object
loan              41188 non-null object
contact           41188 non-null object
month             41188 non-null object
day_of_week       41188 non-null object
duration          41188 non-null int64
campaign          41188 non-null int64
pdays             41188 non-null int64
previous          41188 non-null int64
poutcome          41188 non-null object
emp_var_rate      41188 non-null float64
cons_price_idx    41188 non-null float64
cons_conf_idx     41188 non-null float64
euribor3m         41188 non-null float64
nr_employed       41188 non-null float64
y                 41188 non-null int64
dtypes: float64(5), int64(6), object(10)
memory usag

In [5]:
df['job'].unique()

array(['blue-collar', 'technician', 'management', 'services', 'retired',
       'admin.', 'housemaid', 'unemployed', 'entrepreneur',
       'self-employed', 'unknown', 'student'], dtype=object)

In [6]:
df['job'].replace('blue-collar',1,inplace=True)
df['job'].replace('technician',2,inplace=True)
df['job'].replace('management',3,inplace=True)
df['job'].replace('services',4,inplace=True)
df['job'].replace('retired',5,inplace=True)
df['job'].replace('admin.',6,inplace=True)
df['job'].replace('housemaid',7,inplace=True)
df['job'].replace('unemployed',8,inplace=True)
df['job'].replace('entrepreneur',9,inplace=True)
df['job'].replace('self-employed',10,inplace=True)
df['job'].replace('unknown',11,inplace=True)
df['job'].replace('student',12,inplace=True)

In [7]:
df['marital'].unique()

array(['married', 'single', 'divorced', 'unknown'], dtype=object)

In [8]:
df['marital'].replace('married',1,inplace=True)
df['marital'].replace('single',2,inplace=True)
df['marital'].replace('divorced',3,inplace=True)
df['marital'].replace('unknown',4,inplace=True)

In [9]:
df['education'].unique()

array(['basic.4y', 'unknown', 'university.degree', 'high.school',
       'basic.9y', 'professional.course', 'basic.6y', 'illiterate'],
      dtype=object)

In [10]:
df['education'].replace('basic.4y',1,inplace=True)
df['education'].replace('unknown',2,inplace=True)
df['education'].replace('university.degree',3,inplace=True)
df['education'].replace('high.school',4,inplace=True)
df['education'].replace('basic.9y',5,inplace=True)
df['education'].replace('professional.course',6,inplace=True)
df['education'].replace('basic.6y',7,inplace=True)
df['education'].replace('illiterate',8,inplace=True)


In [11]:
df['default'].unique()

array(['unknown', 'no', 'yes'], dtype=object)

In [12]:
df['default'].replace('unknown',1,inplace=True)
df['default'].replace('no',2,inplace=True)
df['default'].replace('yes',3,inplace=True)


In [13]:
df['housing'].unique()

array(['yes', 'no', 'unknown'], dtype=object)

In [14]:
df['housing'].replace('yes',1,inplace=True)
df['housing'].replace('no',2,inplace=True)
df['housing'].replace('unknown',3,inplace=True)



In [15]:
df['loan'].unique()

array(['no', 'yes', 'unknown'], dtype=object)

In [16]:
df['loan'].replace('no',1,inplace=True)
df['loan'].replace('yes',2,inplace=True)
df['loan'].replace('unknown',3,inplace=True)




In [17]:
df['contact'].unique()

array(['cellular', 'telephone'], dtype=object)

In [18]:
df['contact'].replace('cellular',1,inplace=True)
df['contact'].replace('telephone',2,inplace=True)

In [19]:
df['month'].unique()

array(['aug', 'nov', 'jun', 'apr', 'jul', 'may', 'oct', 'mar', 'sep',
       'dec'], dtype=object)

In [20]:
df['month'].replace('aug',1,inplace=True)
df['month'].replace('nov',2,inplace=True)
df['month'].replace('jun',3,inplace=True)
df['month'].replace('apr',4,inplace=True)
df['month'].replace('jul',5,inplace=True)
df['month'].replace('may',6,inplace=True)
df['month'].replace('oct',7,inplace=True)
df['month'].replace('mar',8,inplace=True)
df['month'].replace('sep',9,inplace=True)
df['month'].replace('dec',10,inplace=True)


In [21]:
df['day_of_week'].unique()

array(['thu', 'fri', 'tue', 'mon', 'wed'], dtype=object)

In [22]:
df['day_of_week'].replace('thu',1,inplace=True)
df['day_of_week'].replace('fri',2,inplace=True)
df['day_of_week'].replace('tue',3,inplace=True)
df['day_of_week'].replace('mon',4,inplace=True)
df['day_of_week'].replace('wed',5,inplace=True)

In [23]:
df['poutcome'].unique()

array(['nonexistent', 'success', 'failure'], dtype=object)

In [24]:
df['poutcome'].replace('nonexistent',1,inplace=True)
df['poutcome'].replace('success',2,inplace=True)
df['poutcome'].replace('failure',3,inplace=True)

In [25]:
df.head()

age  job  marital  education  default  housing  loan  contact  month  \
0   44    1        1          1        1        1     1        1      1   
1   53    2        1          2        2        2     1        1      2   
2   28    3        2          3        2        1     1        1      3   
3   39    4        1          4        2        2     1        1      4   
4   55    5        1          1        2        1     1        1      1   

   day_of_week  ...  campaign  pdays  previous  poutcome  emp_var_rate  \
0            1  ...         1    999         0         1           1.4   
1            2  ...         1    999         0         1          -0.1   
2            1  ...         3      6         2         2          -1.7   
3            2  ...         2    999         0         1          -1.8   
4            2  ...         1      3         1         2          -2.9   

   cons_price_idx  cons_conf_idx  euribor3m  nr_employed  y  
0          93.444          -36.1      4.963       5228.1  0  
1          93.200          -42.0      4.021       5195.8  0  
2          94.055          -39.8      0.729       4991.6  1  
3          93.075          -47.1      1.405       5099.1  0  
4          92.201          -31.4      0.869       5076.2  1  

[5 rows x 21 columns]

In [26]:
X=df.iloc[:,0:-1].values
y=df.iloc[:,-1].values

In [27]:
X

array([[ 4.4000e+01,  1.0000e+00,  1.0000e+00, ..., -3.6100e+01,
         4.9630e+00,  5.2281e+03],
       [ 5.3000e+01,  2.0000e+00,  1.0000e+00, ..., -4.2000e+01,
         4.0210e+00,  5.1958e+03],
       [ 2.8000e+01,  3.0000e+00,  2.0000e+00, ..., -3.9800e+01,
         7.2900e-01,  4.9916e+03],
       ...,
       [ 4.2000e+01,  6.0000e+00,  2.0000e+00, ..., -3.6400e+01,
         4.8570e+00,  5.1910e+03],
       [ 4.8000e+01,  2.0000e+00,  1.0000e+00, ..., -2.6900e+01,
         7.4200e-01,  5.0175e+03],
       [ 2.5000e+01,  1.2000e+01,  2.0000e+00, ..., -3.6400e+01,
         4.8590e+00,  5.1910e+03]])

In [28]:
y

array([0, 0, 1, ..., 0, 0, 0])

In [29]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [30]:
from sklearn.preprocessing import StandardScaler 
sc=StandardScaler()
X_train=sc.fit_transform(X_train) 
X_test=sc.transform(X_test)




In [31]:
classifier=LogisticRegression(random_state=0)
classifier.fit(X_train,y_train)

/Users/mahimasingh/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [32]:
y_pred=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [33]:
cm

array([[7139,  186],
       [ 535,  378]])

In [34]:
classifier.score(X_test,y_test)



0.9124787569798495

In [35]:
pca=PCA(n_components=3)
fit=pca.fit(X)
#to find best volumn
Xbest=pca.fit_transform(X)

In [36]:
print(f"Explained Variance:{fit.explained_variance_ratio_}")

Explained Variance:[0.62683739 0.33086002 0.04085385]


In [37]:
Xbest=pca.fit_transform(X)

In [38]:
trainx,testx,trainy,testy=train_test_split(Xbest,y,test_size=0.2,random_state=0)
model=LogisticRegression()
model.fit(trainx,trainy)
ypred=model.predict(testx)
print(model.score(testx,testy))
print(confusion_matrix(testy,ypred))

0.909686817188638
[[7152  173]
 [ 571  342]]


/Users/mahimasingh/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
